DROP USER user_mmdb CASCADE;

CREATE USER user_mmdb IDENTIFIED BY user_mmdb;
GRANT CONNECT TO user_mmdb;
GRANT CREATE TABLE TO user_mmdb;
GRANT UNLIMITED TABLESPACE TO user_mmdb;
GRANT CREATE ANY DIRECTORY TO user_mmdb;
GRANT CREATE PROCEDURE TO user_mmdb;
GRANT CREATE OPERATOR TO user_mmdb;
GRANT CREATE INDEXTYPE TO user_mmdb;
GRANT CREATE ANY INDEX TO user_mmdb;
ALTER SYSTEM SET JAVA_JIT_ENABLED = FALSE;

DROP TABLE user_mmdb.IMAGES_TABLE;

CREATE TABLE user_mmdb.IMAGES_TABLE
( 
  IMAGE_ID VARCHAR2(500),
  FILE_PATH VARCHAR2(500) NOT NULL,
  PRIMARY KEY (IMAGE_ID)
);

DROP DIRECTORY OMD;
CREATE OR REPLACE DIRECTORY OMD as '/corel-10k';
GRANT READ ON DIRECTORY OMD to PUBLIC;

DECLARE 
V_FILE UTL_FILE.FILE_TYPE;
V_ID NUMBER := 0;
V_PATH VARCHAR2(500);
BEGIN
  DELETE FROM user_mmdb.IMAGES_TABLE;
  V_FILE := UTL_FILE.FOPEN('OMD','images.txt','R');
  IF UTL_FILE.IS_OPEN(V_FILE) THEN
    LOOP
      BEGIN
        UTL_FILE.GET_LINE(V_FILE, V_PATH);
        INSERT INTO user_mmdb.IMAGES_TABLE (IMAGE_ID, FILE_PATH) VALUES (V_ID, TO_CHAR(V_PATH));
        V_ID := V_ID+1;
        IF V_PATH IS NULL THEN
          EXIT;
        END IF;
        EXCEPTION WHEN No_Data_Found THEN EXIT;
      END;
    END LOOP;
    COMMIT;
  END IF;
  UTL_FILE.FCLOSE(V_FILE);
END;
/
