CREATE OR REPLACE FUNCTION SIMILARITY (image1 IN VARCHAR2, 
	images2 IN  VARCHAR2, 
	ctx IN SYS.ODCIINDEXCTX, 
	sctx IN OUT IMAGE_INDEX, 
	scanflg IN NUMBER
	) RETURN NUMBER AS
LANGUAGE JAVA
NAME 'Similarity.similarity (java.lang.String, java.lang.String, oracle.ODCI.ODCIIndexCtx, Index[], java.math.BigDecimal) return java.math.BigDecimal';
/

DROP OPERATOR SIMILARITYOPERATOR;

CREATE OR REPLACE OPERATOR SIMILARITYOPERATOR
BINDING (VARCHAR2, VARCHAR2) RETURN NUMBER 
WITH INDEX CONTEXT, SCAN CONTEXT IMAGE_INDEX
USING SIMILARITY;
DROP INDEXTYPE IMAGE_INDEX_TYPE;

GRANT ALL PRIVILEGES ON SIMILARITYOPERATOR TO USER_MMDB;

CREATE OR REPLACE INDEXTYPE IMAGE_INDEX_TYPE
FOR SIMILARITYOPERATOR (VARCHAR2, VARCHAR2)
USING IMAGE_INDEX
WITH SYSTEM MANAGED STORAGE TABLES;

DROP INDEX IMAGES_TABLE_INDEX;

CREATE INDEX IAMGES_TABLE_INDEX ON IMAGES_TABLE(FILE_PATH)
INDEXTYPE IS IMAGE_INDEX_TYPE;
 
exit 0;
